server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: $PROMTAIL-DATA-LOCATION/positions.yaml # This location needs to be writeable by Promtail.

client:
  url: http://$GEL-GATEWAY-URL:3100/loki/api/v1/push
  basic_auth:
    username: $GEL-INSTANCE-INTERNAL-NAME
    password: $GEL-INSTANCE-ACCESSPOLICY-TOKEN
    
scrape_configs:
 - job_name: system
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: varlogs  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
      host: $HOSTNAME # A `host` label will help identify logs from this machine vs others
      __path__: /var/log/*.log  # The path matching uses a third party library: https://github.com